include: "rules/common.smk"


rule all:
    input:
        get_targets(),


if TO_CLEAN_FQ:

    include: "rules/qc/fastp.smk"


include: "rules/qc/qc.smk"
include: f"rules/mapper/{MAPPER}.smk"
include: "rules/gatk/mark_duplicates.smk"
include: "rules/gatk/base_recalibration.smk"
include: "rules/mapper/bwa.smk"


for caller in CALLERS:

    include: f"rules/caller/{caller}.smk"


include: "rules/annotator/cache.smk"


for annotator in ANNOTATORS:

    include: f"rules/annotator/{annotator}.smk"


include: "rules/filtration/duphold.smk"
include: "rules/filtration/hard_filter.smk"
include: "rules/filtration/separate_types.smk"
include: "rules/filtration/survivor.smk"
include: "rules/filtration/extract_annotations.smk"
include: "rules/filtration/convert_annotations.smk"
include: "rules/filtration/filter_annotations.smk"
include: "rules/filtration/survivor_final.smk"
