include: "rules/common.smk"


rule all:
    input:
        get_targets(),


if TO_CLEAN_FQ:

    include: "rules/qc/fastp.smk"


include: "rules/qc/qc.smk"
include: f"rules/mapper/{MAPPER}.smk"
include: "rules/gatk/mark_duplicates.smk"
include: "rules/gatk/base_recalibration.smk"
include: "rules/mapper/bwa.smk"


for caller in CALLERS_SV:

    include: f"rules/caller/sv/{caller}.smk"


for caller in CALLERS_MUTATION:

    include: f"rules/caller/mutation/{caller}.smk"


include: "rules/gatk/learn_read_orientation_model.smk"
include: "rules/gatk/calculate_contamination.smk"
include: "rules/annotator/cache.smk"


for annotator in ANNOTATORS:

    include: f"rules/annotator/{annotator}.smk"


include: "rules/filtration/sv/duphold.smk"
include: "rules/filtration/sv/hard_filter.smk"
include: "rules/filtration/sv/separate_types.smk"
include: "rules/filtration/sv/survivor.smk"
include: "rules/filtration/sv/extract_annotations.smk"
include: "rules/filtration/sv/convert_annotations.smk"
include: "rules/filtration/sv/filter_annotations.smk"
include: "rules/filtration/sv/survivor_final.smk"
include: "rules/filtration/mutation/hard_filter.smk"
include: "rules/filtration/mutation/extract_annotations.smk"
include: "rules/filtration/mutation/convert_annotations.smk"
